---
title: "Least Sqaures Guess vs OLS"
author: "*Prepared by:* Matthew E. Vanaman"
date: '`r format(Sys.Date(), "%m-%d-%Y")`'
monofont: "Fira Code"
output: 
  bookdown::html_document2:
    toc: yes
    toc_depth: 3
    fig_caption: yes
    number_sections: no
    code_folding: hide
    theme:
      code_font: 
        google: Fira Code
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, warning = FALSE, message = FALSE)
library(tidyverse)
library(wesanderson)
library(shiny)
```


# to do

- DONE create plot function 
- DONE create function to calculate sums of squares etc. 
- DONE create app that plots scatter plot with slope and y-intercept 
- print regression table
- print data values table
- add options:
  - want residual lines to guess line?
  - want residual lines to best line?
  - want to label data points?


```{r}
plot_guess <- function(slope, y_intercept, tab){
  # get data
  x <- 1:10
  y <- c(2, 1, 5, 3, 6, 4, 8, 10, 7, 9)
  # predict from best fit
  best <- lm(y ~ x)
  # predict from the user-guessed line of fit
  slope <- slope
  y_intercept <- y_intercept
  y_hat <- y_intercept + (slope * x)
  # calculate user-guessed sums of squares
  y_resid <- y - y_hat
  y_resid_sq <- y_resid^2
  SSs <- sum(y_resid_sq)
  # combine into table
  tab <- tibble(
    "Data Point" = 1:10,
    X = x, 
    Y = y, 
    "Predicted (Guess)" = y_hat, 
    "Predicted (Best Fit)" = best$fitted.values,
    "Residuals (Guess)" = y_resid,
    "Residuals (Best Fit)" = best$residuals, 
    "Squared Residuals (Guess)" = y_resid_sq,
    "Squared Residuals (Best Fit)" = best$residuals^2,
  )
  # summary Stats
  SSs <- tibble("Sum of Sqaured Residuals" = c(sum(tab$`Squared Residuals (Guess)`), sum(tab$`Squared Residuals (Best Fit)`)))
  regression_guess <- tibble(Slope = slope,  "Y-Intercept" = y_intercept)
  regression_best <- tibble(Slope = best$coefficients["x"],"Y-Intercept" = best$coefficients["(Intercept)"])
  regression <- bind_rows(regression_guess, regression_best)
  reg_table <- cbind(Line = c("Guess", "Best Fit"), regression, SSs)
  
  # display plot
  plot <- ggplot(tab, aes(x = X, y = Y)) +
    geom_point(alpha = 0.5) +
    geom_abline(data = reg_table, aes(slope = Slope, intercept = `Y-Intercept`, color = Line), size = 1, show.legend = TRUE) +
    # connects dots to line of best fit; add in using ifelse down the line
    # geom_segment(aes(x = X, y = Y, xend = X, yend = `Predicted (Best Fit)`), linetype = "dashed", color = "#798E87", alpha = 0.75) +
    # connects dots to line of best guess
    geom_segment(aes(x = X, y = Y, xend = X, yend = `Predicted (Guess)`), linetype = "dashed", color = "#C27D38", alpha = 0.75) +
    geom_text(aes(label = `Data Point`), hjust = -1) +
    theme_classic() +
    theme(legend.position = "top") +
    scale_color_manual(values = wes_palette(2, name = "Moonrise2", type = "discrete"), name = "")
  
  return(
    list(
      table = tab,
      plot = plot,
      reg_table = reg_table
      )
    )
}


ui <- fluidPage(
  fluidRow(
    column(
      1, # column width on page
      numericInput( # 1st (and only) entry in this column
        "slope", # object name that gets referred to in server
        label = "Guess the Slope", # label displayed to user above text box
        value = 0, # default value of the text box
        min = -100 # minimum possible value for text box
      )
    ),
    column(1, numericInput("y_intercept", label = "Guess the Y-Intercept", value = 0, min = -100)), # 2nd entry in column
  ),
  fluidRow(
    column(5, plotOutput("scatterplot"))
    # column(3, verbatimTextOutput("ttest"))
  )
)

server <- function(input, output, session) {
  # create objects to use later
  # wrapping in the reactive({}) funtion lets you re-used object
  slope <- reactive({input$slope})
  y_intercept <- reactive({input$y_intercept})
  guess_data <- reactive({plot_guess(slope = slope(), y_intercept = y_intercept())})
  
  output$scatterplot <- renderPlot({
    guess_data()
      }, res = 96)

  output$ttest <- renderText({
    x1 <- rnorm(input$n1, input$mean1, input$sd1)
    x2 <- rnorm(input$n2, input$mean2, input$sd2)

    t_test(x1, x2)
  })
}

shinyApp(ui = ui, server = server)
```

```{r}
# freqpoly <- function(x1, x2, binwidth = 0.1, xlim = c(-3, 3)) {
#   df <- data.frame(
#     x = c(x1, x2),
#     g = c(rep("x1", length(x1)), rep("x2", length(x2)))
#   )
# 
#   ggplot(df, aes(x, colour = g)) +
#     geom_freqpoly(binwidth = binwidth, size = 1) +
#     coord_cartesian(xlim = xlim)
# }
# 
# t_test <- function(x1, x2) {
#   test <- t.test(x1, x2)
#   
#   # use sprintf() to format t.test() results compactly
#   sprintf(
#     "p value: %0.3f\n[%0.2f, %0.2f]",
#     test$p.value, test$conf.int[1], test$conf.int[2]
#   )
# }
# 
# 
# 
# ui <- fluidPage(
#   fluidRow(
#     column(4, 
#       "Distribution 1",
#       numericInput("n1", label = "n", value = 1000, min = 1),
#       numericInput("mean1", label = "µ", value = 0, step = 0.1),
#       numericInput("sd1", label = "σ", value = 0.5, min = 0.1, step = 0.1)
#     ),
#     column(4, 
#       "Distribution 2",
#       numericInput("n2", label = "n", value = 1000, min = 1),
#       numericInput("mean2", label = "µ", value = 0, step = 0.1),
#       numericInput("sd2", label = "σ", value = 0.5, min = 0.1, step = 0.1)
#     ),
#     column(4,
#       "Frequency polygon",
#       numericInput("binwidth", label = "Bin width", value = 0.1, step = 0.1),
#       sliderInput("range", label = "range", value = c(-3, 3), min = -5, max = 5)
#     )
#   ),
#   fluidRow(
#     column(9, plotOutput("hist")),
#     column(3, verbatimTextOutput("ttest"))
#   )
# )
# 
# server <- function(input, output, session) {
#   output$hist <- renderPlot({
#     x1 <- rnorm(input$n1, input$mean1, input$sd1)
#     x2 <- rnorm(input$n2, input$mean2, input$sd2)
#     
#     freqpoly(x1, x2, binwidth = input$binwidth, xlim = input$range)
#   }, res = 96)
# 
#   output$ttest <- renderText({
#     x1 <- rnorm(input$n1, input$mean1, input$sd1)
#     x2 <- rnorm(input$n2, input$mean2, input$sd2)
#     
#     t_test(x1, x2)
#   })
# }
# 
# shinyApp(ui = ui, server = server)

```

